#!/bin/bash
# reboots to windows

if [ "$1" = "-h" ]
then
echo "-----------------------------------Winboot Version 2.0.0---------------------------------------"
echo " "
echo "Usage:"
echo " "
echo "-h (brings this screen)"
echo "-install (initial one-time only installation)"
echo "-update (updates to latest version from repository)"
echo " "
echo "Configuration Notes:"
echo " "
echo "Winboot needs a little configuration change in /etc/default/grub to work:"
echo "Step 1: Edit the grub configuration file by running: sudo gedit /etc/default/grub"
echo "Step 2: Change the GRUB_DEFAULT parameter so it says GRUB_DEFAULT=\"saved\" then save&exit"

echo " "
echo "Disclaimer:" 
echo "Winboot assumes Windows is the second entry on your grub menu (entry number 1, counting from 0), "
echo "if your setup is different, please change line 50 in the source code to match your preferences! "
echo " "
echo "--------------------------------------------------------------------------------------------------"
elif [ "$1" = "-install" ] #installation
then
chmod 755 winboot
sudo cp winboot /bin
sudo cp entry.cfg /bin
cd ..
rm -rf Winboot
echo "  "
echo "Latest Winboot version is succesfully installed!"
winboot -h
exit 1
elif  [ "$1" = "-update" ] #update to latest version
then
git clone https://github.com/semiismaili/Winboot.git
cd Winboot
chmod 755 winboot
sudo cp winboot /bin
sudo cp entry.cfg /bin
cd ..
rm -rf Winboot
echo "  "
echo "Latest Winboot version is succesfully installed!"
exit 1
elif [ "$1" = "-set" ] #entry set
then
       if [ "$2" -ge 0 ] 
       then
       entry=$2
       echo $entry > entry.cfg
       exit 1
       else
        echo "Second argument should be a number!"
       fi
exit 1
elif [ $# -eq 0 ] 
then #actual work
echo "Enter password to reboot to Windows!"
$entry=`cat entry.cfg`
sudo grub-reboot $entry #winboot assumes Windows is the second entry on your grub menu, 
                    #change 1 to your own Windows entry number (counting from 0)
counter=3
echo -n "Rebooting to Windows in "
while [ "$counter" -gt 1 ]
do
echo  -n "$counter..."
counter=$(($counter - 1))
sleep 1
done
echo "1"
reboot
else
echo "Invalid argument, please use winboot -h for help!"
fi
