#!/usr/bin/bash

git clone https://github.com/semiismaili/Winboot.git
cd Winboot
chmod 755 winboot
sudo cp winboot /bin
cd ..
rm -rf Winboot
echo "  "
echo "Latest Winboot version is succesfully installed!"
winboot -h
exit
