#!/usr/bin/bash
#cd $HOME
#git clone https://github.com/semiismaili/Winboot.git
#cd Winboot
chmod 755 winboot
sudo cp winboot /bin
cd ..
rm -rf Winboot
echo "  "
echo "Winboot is succesfully installed!"
winboot -h
exit
